print("Hello World")
print(100+50)
print(1000)

print('Luis'+' '+'Muñoz')
print('My name is \'Luis\'')
print('My name is:\nLuis Muñoz')
print('My name is \n\t Luis')
print('This isn\'t a number')
print('This isgn \\ is a backslash')